spring:
  application:
    name: shoestore

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shoestore?useSSL=false&serverTimezone=UTC&characterEncoding=utf8 
    username: root
    password: "123456"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
